/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gswat_main_window (void);
GtkWidget* create_gswat_new_session_window (void);
GtkWidget* create_gswat_new_session_dialog (void);
